export default {
  // local secret key
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  JWT_SECRET_KEY: 'JWT_SECRET_KEY',
  SECRET_KEY: 'SECRET_KEY',

  // mysql connect
  MYSQL_DB_NAME: 'MYSQL_DB_NAME',
  MYSQL_DB_USER: 'MYSQL_DB_USER',
  MYSQL_DB_PASSWORD: 'MYSQL_DB_PASSWORD',
  MYSQL_DB_PORT: 'MYSQL_DB_PORT',
  MYSQL_DB_HOST: 'MYSQL_DB_HOST',

  // default user
  DEFAULT_USER_EMAIL: 'DEFAULT_USER_EMAIL',
  DEFAULT_USER_PASSWORD: 'DEFAULT_USER_PASSWORD',
  DEFAULT_API_KEY: 'DEFAULT_API_KEY',
  DEFAULT_SECRET_KEY: 'DEFAULT_SECRET_KEY',

  // binance api
  BINANCE_BASE_URL: 'BINANCE_BASE_URL',
  LOCAL_BASE_URL: 'LOCAL_BASE_URL',

  // bot key
  SECRET_KEY_BOT: 'SECRET_KEY_BOT',
}
